# Generated by Django 2.2.2 on 2019-06-11 16:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Projection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reserved_seats', models.TextField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='finished', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationCanceled',
            fields=[
                ('reservationstate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.ReservationState')),
            ],
            bases=('reservations.reservationstate',),
        ),
        migrations.CreateModel(
            name='ReservationFinished',
            fields=[
                ('reservationstate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.ReservationState')),
            ],
            bases=('reservations.reservationstate',),
        ),
        migrations.CreateModel(
            name='ReservationSelected',
            fields=[
                ('reservationstate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reservations.ReservationState')),
            ],
            bases=('reservations.reservationstate',),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('num_columns', models.IntegerField(default=20)),
                ('num_rows', models.IntegerField(default=20)),
                ('prices', models.TextField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.Cinema')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('seats', models.TextField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('projection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.Projection')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.ReservationState')),
            ],
        ),
        migrations.AddField(
            model_name='projection',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservations.Room'),
        ),
    ]
